export const hiragana = [
  { kana: "あ", roma: "a" }, { kana: "い", roma: "i" }, { kana: "う", roma: "u" }, { kana: "え", roma: "e" }, { kana: "お", roma: "o" },
  { kana: "か", roma: "ka" }, { kana: "き", roma: "ki" }, { kana: "く", roma: "ku" }, { kana: "け", roma: "ke" }, { kana: "こ", roma: "ko" },
  { kana: "さ", roma: "sa" }, { kana: "し", roma: "shi" }, { kana: "す", roma: "su" }, { kana: "せ", roma: "se" }, { kana: "そ", roma: "so" },
  { kana: "た", roma: "ta" }, { kana: "ち", roma: "chi" }, { kana: "つ", roma: "tsu" }, { kana: "て", roma: "te" }, { kana: "と", roma: "to" },
  { kana: "な", roma: "na" }, { kana: "に", roma: "ni" }, { kana: "ぬ", roma: "nu" }, { kana: "ね", roma: "ne" }, { kana: "の", roma: "no" },
  { kana: "は", roma: "ha" }, { kana: "ひ", roma: "hi" }, { kana: "ふ", roma: "fu" }, { kana: "へ", roma: "he" }, { kana: "ほ", roma: "ho" },
  { kana: "ま", roma: "ma" }, { kana: "み", roma: "mi" }, { kana: "む", roma: "mu" }, { kana: "め", roma: "me" }, { kana: "も", roma: "mo" },
  { kana: "や", roma: "ya" }, { kana: "", roma: "" }, { kana: "ゆ", roma: "yu" }, { kana: "", roma: "" }, { kana: "よ", roma: "yo" },
  { kana: "ら", roma: "ra" }, { kana: "り", roma: "ri" }, { kana: "る", roma: "ru" }, { kana: "れ", roma: "re" }, { kana: "ろ", roma: "ro" },
  { kana: "わ", roma: "wa" }, { kana: "", roma: "" }, { kana: "", roma: "" }, { kana: "", roma: "" }, { kana: "を", roma: "wo" },
  { kana: "ん", roma: "n" }
];

export const katakana = [
  { kana: "ア", roma: "a" }, { kana: "イ", roma: "i" }, { kana: "ウ", roma: "u" }, { kana: "エ", roma: "e" }, { kana: "オ", roma: "o" },
  { kana: "カ", roma: "ka" }, { kana: "キ", roma: "ki" }, { kana: "ク", roma: "ku" }, { kana: "ケ", roma: "ke" }, { kana: "コ", roma: "ko" },
  { kana: "サ", roma: "sa" }, { kana: "シ", roma: "shi" }, { kana: "ス", roma: "su" }, { kana: "セ", roma: "se" }, { kana: "ソ", roma: "so" },
  { kana: "タ", roma: "ta" }, { kana: "チ", roma: "chi" }, { kana: "ツ", roma: "tsu" }, { kana: "テ", roma: "te" }, { kana: "ト", roma: "to" },
  { kana: "ナ", roma: "na" }, { kana: "ニ", roma: "ni" }, { kana: "ヌ", roma: "nu" }, { kana: "ネ", roma: "ne" }, { kana: "ノ", roma: "no" },
  { kana: "ハ", roma: "ha" }, { kana: "ヒ", roma: "hi" }, { kana: "フ", roma: "fu" }, { kana: "ヘ", roma: "he" }, { kana: "ホ", roma: "ho" },
  { kana: "マ", roma: "ma" }, { kana: "ミ", roma: "mi" }, { kana: "ム", roma: "mu" }, { kana: "メ", roma: "me" }, { kana: "モ", roma: "mo" },
  { kana: "ヤ", roma: "ya" }, { kana: "", roma: "" }, { kana: "ユ", roma: "yu" }, { kana: "", roma: "" }, { kana: "ヨ", roma: "yo" },
  { kana: "ラ", roma: "ra" }, { kana: "リ", roma: "ri" }, { kana: "ル", roma: "ru" }, { kana: "レ", roma: "re" }, { kana: "ロ", roma: "ro" },
  { kana: "ワ", roma: "wa" }, { kana: "", roma: "" }, { kana: "", roma: "" }, { kana: "", roma: "" }, { kana: "ヲ", roma: "wo" },
  { kana: "ン", roma: "n" }
];

export const n5Kanji = [
  { character: "日", reading: "nichi / hi", meaning: "sun; day" },
  { character: "月", reading: "getsu / tsuki", meaning: "moon; month" },
  { character: "人", reading: "jin / hito", meaning: "person" },
  { character: "水", reading: "sui / mizu", meaning: "water" },
  { character: "木", reading: "moku / ki", meaning: "tree" },
  { character: "金", reading: "kin / kane", meaning: "gold; money" },
  { character: "土", reading: "do / tsuchi", meaning: "soil; earth" },
  { character: "山", reading: "san / yama", meaning: "mountain" },
  { character: "川", reading: "sen / kawa", meaning: "river" },
  { character: "本", reading: "hon", meaning: "book; origin" },
  { character: "火", reading: "ka / hi", meaning: "fire" },
  { character: "気", reading: "ki", meaning: "spirit; energy" },
  { character: "天", reading: "ten", meaning: "heaven; sky" },
  { character: "生", reading: "sei / umares", meaning: "life; birth" },
  { character: "先", reading: "sen / saki", meaning: "ahead; previous" },
  { character: "名", reading: "mei / na", meaning: "name" },
  { character: "白", reading: "haku / shiro", meaning: "white" },
  { character: "大", reading: "dai / oo", meaning: "big" },
  { character: "小", reading: "shou / chii", meaning: "small" },
  { character: "古", reading: "ko / furu", meaning: "old" },
  { character: "新", reading: "shin / atara", meaning: "new" },
  { character: "国", reading: "koku / kuni", meaning: "country" },
  { character: "長", reading: "chou / naga", meaning: "long; leader" },
  { character: "東", reading: "tou / higashi", meaning: "east" },
  { character: "西", reading: "sei / nishi", meaning: "west" },
  { character: "南", reading: "nan / minami", meaning: "south" },
  { character: "北", reading: "hoku / kita", meaning: "north" },
  { character: "高", reading: "kou / taka", meaning: "high; expensive" },
  { character: "外", reading: "gai / soto", meaning: "outside" },
  { character: "内", reading: "nai / uchi", meaning: "inside" },
  { character: "中", reading: "chuu / naka", meaning: "middle; inside" },
  { character: "半", reading: "han", meaning: "half" },
  { character: "分", reading: "bun / fun / wa", meaning: "part; minute; understand" },
  { character: "上", reading: "jou / ue", meaning: "up; above" },
  { character: "下", reading: "ka / shita", meaning: "down; below" },
  { character: "前", reading: "zen / mae", meaning: "before; front" },
  { character: "後", reading: "go / ushiro", meaning: "after; behind" },
  { character: "午", reading: "go", meaning: "noon" },
  { character: "今", reading: "kon / ima", meaning: "now" },
  { character: "何", reading: "ka / nani", meaning: "what" },
  { character: "校", reading: "kou", meaning: "school" },
  { character: "語", reading: "go / kata", meaning: "language; word" },
  { character: "行", reading: "kou / i", meaning: "go" },
  { character: "来", reading: "rai / ku", meaning: "come" },
  { character: "出", reading: "shutsu / de", meaning: "exit; go out" },
  { character: "入", reading: "nyuu / hai", meaning: "enter; put in" },
  { character: "見", reading: "ken / mi", meaning: "see; look" },
  { character: "聞", reading: "bun / ki", meaning: "hear; listen" },
  { character: "食", reading: "shoku / ta", meaning: "eat" },
  { character: "飲", reading: "in / no", meaning: "drink" }
];

export const n4Kanji = [
  { character: "駅", reading: "eki", meaning: "station" },
  { character: "店", reading: "ten / mise", meaning: "shop" },
  { character: "病", reading: "byou", meaning: "illness" },
  { character: "強", reading: "kyou / tsuyoi", meaning: "strong" },
  { character: "弱", reading: "jaku / yowai", meaning: "weak" },
  { character: "道", reading: "dou / michi", meaning: "road; way" },
  { character: "会", reading: "kai / a", meaning: "meet" },
  { character: "同", reading: "dou / ona", meaning: "same" },
  { character: "事", reading: "ji / koto", meaning: "thing; matter" },
  { character: "自", reading: "ji / shi", meaning: "self" },
  { character: "社", reading: "sha", meaning: "company" },
  { character: "発", reading: "hatsu", meaning: "departure; emit" },
  { character: "者", reading: "sha / mono", meaning: "person" },
  { character: "地", reading: "chi / ji", meaning: "ground; earth" },
  { character: "業", reading: "gyou", meaning: "business; industry" },
  { character: "方", reading: "hou / kata", meaning: "direction; person" },
  { character: "新", reading: "shin / atara", meaning: "new" },
  { character: "場", reading: "jou / ba", meaning: "place" },
  { character: "員", reading: "in", meaning: "member" },
  { character: "立", reading: "ritsu / ta", meaning: "stand" },
  { character: "開", reading: "kai / a", meaning: "open" },
  { character: "出", reading: "shutsu / de", meaning: "exit; go out" },
  { character: "代", reading: "dai / ka", meaning: "substitute; age" },
  { character: "力", reading: "ryoku / chikara", meaning: "power; strength" },
  { character: "通", reading: "tsuu / tou", meaning: "pass through" },
  { character: "動", reading: "dou / ugo", meaning: "move" },
  { character: "建", reading: "ken / ta", meaning: "build" },
  { character: "言", reading: "gen / i", meaning: "say" },
  { character: "米", reading: "bei / kome", meaning: "rice; America" },
  { character: "明", reading: "mei / aka", meaning: "bright; clear" },
  { character: "京", reading: "kyou", meaning: "capital" },
  { character: "理", reading: "ri", meaning: "reason; logic" },
  { character: "体", reading: "tai / karada", meaning: "body" },
  { character: "主", reading: "shu / nushi", meaning: "master; main" },
  { character: "題", reading: "dai", meaning: "topic; subject" },
  { character: "意", reading: "i", meaning: "mind; meaning" },
  { character: "不", reading: "fu", meaning: "not; non-" },
  { character: "作", reading: "saku / tsuku", meaning: "make" },
  { character: "用", reading: "you", meaning: "use" },
  { character: "度", reading: "do", meaning: "degree; times" }
];
